### ISSUE TITLE
add list of functions to documentation

### ISSUE THREAD

**Issue by lacava** [cavalab/feat#239]
make the list of available functions easier to find!

**Comment by folivetti** [comment]
please do :-D
Just to add to this issue, if I pass a wrong name for a function, the algorithm seems to enter an infinite loop. Example code:

```python
import numpy as np
from feat import FeatRegressor

x = np.arange(-1, 1, 0.1)
y = np.sin(x)

est = FeatRegressor(pop_size=10, gens=2, verbosity=1, functions="add,sub,mul,div,exp,log")
est.fit(x.reshape(-1,1),y)
```

After some time I figured it out that it should be `est = FeatRegressor(pop_size=10, gens=2, verbosity=1, functions="+,-,*,/,exp,log")`
