### ISSUE TITLE
Custom function

### ISSUE THREAD

**Issue by arita37** [cavalab/feat#273]
Hello,
Thanks for the repo.
Is there a way to add  custom functions 
primitive ? (Ie based on user expert knowledge).
Thanks

**Comment by lacava** [comment]
hi @arita37 , here is the process:

- create a custom node. You can derive it from the [Node class](https://github.com/lacava/feat/blob/master/src/pop/op/node.h), or if it is differentiable from [NodeDx](https://github.com/lacava/feat/blob/master/src/pop/op/n_Dx.h), or if it "learns" some values during training, from the [NodeTrain class](https://github.com/lacava/feat/blob/master/src/pop/op/n_train.h). 

- add the custom node to [nodemap.h](https://github.com/lacava/feat/blob/master/src/pop/nodemap.h), with a unique string name to reference it.

rerun `./configure` and `./install`. 

- you should now be able to use your node by including it in the `functions` argument passed to `Feat()` class (or `FeatRegressor`/`FeatClassifier`). 

- If you would like to have it included in the functions by default, add the string name of the custom primitive to [this line](https://github.com/lacava/feat/blob/c3f7da75d7646c52d4da45807b2cb97cc7731e06/src/params.cc#L421) in `set_functions`. 

as always, let me know if you run into any issues.
