### ISSUE TITLE
segmentation fault in parallel mode

### ISSUE THREAD

**Issue by arita37** [cavalab/feat#274]
Have many segmentation faults for parallelization ,
as soon as n_jobs > 2 . 

Is this concurrent access issue to the data using pandas ?

`7f4020017000-7f402001d000 r--p 00000000 08:03 18367538                   /.conda/envs/feat-env/lib/python3.8/site-packages/pandas/_libs/tslibAborted (core dumped)`

**Comment by lacava** [comment]
hello. i haven't seen this error before, and yes, it appears to come from pandas. can you provide a minimum working example so i can debug?

**Comment by arita37** [comment]
Using 0.5 version:
Just basic code  also failed.

        X = np.random.rand(100,10)
        y = np.random.rand(100)
        y = [ 1 if t > 0.5 else 0 for t in y ]
        
    fest = Feat(pop_size=10, n_jobs= 5               )

    fest.fit(X_t,y_t)

Maybe due to compilation
I just compile with 

./install

without any flag

**Comment by lacava** [comment]
> Maybe due to compilation
> I just compile with
> 
> ./install
> 
> without any flag

that should work. I'm looking into it now.

**Comment by arita37** [comment]
GCC is 4.80
OS is CentOS

**Comment by lacava** [comment]
I think gcc 4.8 might be the issue. Can you try GCC > 5.2? I've compiled it on CenOS with 5.2 and on Ubuntu 16-18 with gcc 5.4 - gcc 7. I just ran the example without any issues.

**Comment by arita37** [comment]
Thx

Do you know a way to install gcc in a portable way ? (Cannot change my server gcc 4.7)

**Comment by lacava** [comment]
You may be able to use conda: https://anaconda.org/3dhubs/gcc-5
