### ISSUE TITLE
Logistic regression seems falling

### ISSUE THREAD

**Issue by arita37** [cavalab/feat#275]
It seems logistic regression  ml = "LR" seems falling.
We cannot see any test in the code using Binary prediction.

**Comment by lacava** [comment]
That's not good! Can you provide a minimum working example so I can try to reproduce this error?

**Comment by lacava** [comment]
> We cannot see any test in the code using Binary prediction.

Binary classification is tested in the wrapper, https://github.com/lacava/feat/blob/master/tests/wrappertest.py , and I use it regularly in my work without a problem. Please let me know if you are still experiencing this issue or not.
