### ISSUE TITLE
Cartesian Genetic Prog

### ISSUE THREAD

**Issue by arita37** [cavalab/feat#276]
As a suggestion, have you tried
cartesian genetic programming ?

There are a couple of implementation available.

**Comment by lacava** [comment]
I'm familiar with the work of Julian Miller and Dario Izzo, and I've met and chatted with them about their work (e.g., https://www.cartesiangp.com/, https://github.com/darioizzo/dcgp) . Seems like an interesting approach and I would like to benchmark their methods. CGP allows for neutral variation, which is an interesting idea. I explored it a bit in [stack-based genetic programming using an epigenetic layer](http://www.williamlacava.com/pubs/inference_elgp_2015_lacava.pdf). However, I haven't tried out their implementations, and I should.

**Comment by arita37** [comment]
An interesting (and much longer work)
would be using RL + NN 
to control the search process in an exponential search space.
One way to train it is using synthetic data.

**Comment by lacava** [comment]
Hi @arita37 , you can reach me at lacava at penn dot edu.
