### ISSUE TITLE
Operator selection syntax/ issue

### ISSUE THREAD

**Issue by cooperkellyhansen** [cavalab/feat#283]
Hey, love the repo. Its super helpful for my lab that does GPSR on mechanical engineering problems.

I'm wondering how to set the 'functions' parameter without entering an infinite loop. In the package I mainly use (BINGO) the operators are specified as string entries ('+', '-', ...). When I try to customize the operator list in the function parameter of Feat() the code enters an infinite loop. Do you have a better explanation for how to set the operator list?

Thanks,
Cooper

**Comment by samParry** [comment]
I have encountered the same issue. When trying to select which functions to use the program enters an infinite loop printing "**" to the terminal.

Here is a screenshot of my altered version of the "Basic Usage" example from the documentation.
![Screenshot 2022-04-22 103721](https://user-images.githubusercontent.com/71298870/164757229-9b7f58ab-6788-4a5e-bc0c-6afdd304b573.jpg)

And this is the output to the terminal when I run the program.
![Screenshot 2022-04-22 103903](https://user-images.githubusercontent.com/71298870/164757520-a2fdfa67-9e74-4d22-addd-e7c85dd5679b.jpg)

The use of this tool looks very promising but the incomplete documentation and lack of entries in the Python API section has made it difficult to use/understand.

**Comment by lacava** [comment]
> Here is a screenshot of my altered version of the "Basic Usage" example from the documentation.

remove the spaces

> If I change the line above to functions="+,-,/,*,exp,log,sqrt" I get this error instead of the infinite loop.

checking. are the variables still `X = np.random.rand(100,10)`? 

> The use of this tool looks very promising but the incomplete documentation and lack of entries in the Python API section has made it difficult to use/understand.

This is a new documentation issue actually. The API isn't generating. will look into it.

**Comment by samParry** [comment]
Yes, the variables are still the X = np.random.rand(100,10)

Thank you for the quick response.

**Comment by cooperkellyhansen** [comment]
I did a run on a materials properties dataset without the spaces and that worked for me. 

![image](https://user-images.githubusercontent.com/27398310/164762961-409c41ac-b68b-4a2b-9386-171630d4fd31.png)

**Comment by lacava** [comment]
until I fix the API the Python params are documented here: https://github.com/cavalab/feat/blob/master/feat/feat.py

**Comment by cooperkellyhansen** [comment]
Looks like after loading another dataset this issue is still occurring. No syntax changed.  

Same error as above:
![image](https://user-images.githubusercontent.com/27398310/164817530-00ef3c3a-2f53-4f95-8a37-f941fc50514c.png)

**Comment by lacava** [comment]
as a temporary fix, can you try specifying `otype='f'` in `Feat()`?

**Comment by cooperkellyhansen** [comment]
Perfect, that worked. Thanks for the quick response.
