### ISSUE TITLE
Double decimal points in coefficient

### ISSUE THREAD

**Issue by folivetti** [cavalab/feat#287]
Running some experiments, sometimes I get an expression where one or more of the numerical coefficients have two decimal points. I'm assuming they are two numbers with an operator missing. For example:

```
2656.996160.85*(0.0029*(0.2996*log(0.4346*x_1)+0.1809*(0.6970*x_1*x_1))*log(0.3637*(0.8949*x_1-0.4048*x_1)))+-2432.39*exp(0.0745*log(0.7008*x_1))+-162.08*log(0.9116*log(0.0452*x_1))+142.61*log(0.4346*x_1)+1.89*log(0.8586*log(0.3637*(0.8949*x_1-0.4048*x_1)))+1.13*exp(0.4094*(0.0216*(0.4839*x_0*x_0)/0.6391*log(0.1307*x_0)))+0.86*exp(0.4094*(0.4839*x_0*x_0))-0.56*(0.4839*x_0*x_0)+-0.05*log(0.1307*(0.2996*log(0.4346*x_1)+0.1809*(0.6970*log(0.0452*x_1)*x_1)))+-0.01*(0.0976*log(0.1307*x_0)*x_1)
```

Can be obtained using this code and the attached dataset:

```python
import numpy as np
z = np.loadtxt("Pagie.csv", delimiter=",")
x = z[:,:-1]
y = z[:,-1]

est = FeatRegressor(
                    pop_size=500,
                    gens=200,
                    backprop=False,
                    iters=1,
                    max_depth=3,
                    functions="+,-,*,/,exp,log",
                    verbosity=0,
                    random_state=1
                   )

est.fit(x,y)
print(est.get_eqn())
```

I'm installing FEAT with the current srbench script.
[Pagie.csv](https://github.com/cavalab/feat/files/9849891/Pagie.csv)

P.S.: I'm making some experiments with FEAT and possibly will be bothering with issues in the next few weeks :-P

**Comment by lacava** [comment]
Bother away!
This is strange behavior, I haven't seen it before. Is it always at the
beginning? There might just be a plus missing between the offset and the
first term.

**Comment by folivetti** [comment]
I just tried multiple runs and sometimes the operator is missing in the middle of the expression, like

```
6387.32+-6295.98*exp(0.3013*exp(0.8169*log(0.2892*x_0)))+4957.46*(0.0818*(0.0688*x_1*x_0)*(0.6366*x_1/0.8836*x_0))1994.09*exp(0.8279*log(0.2892*x_0))+93.49*exp(0.6516*log(0.0637*x_1))+-66.11*exp(0.4527*(0.4200*x_1*x_1))+23.81*log(0.3233*log(0.0637*x_1))+23.67*(0.3082*(0.6473*x_1*x_1)*(0.4200*x_1*x_1))+18.79*log(0.0637*log(0.0560*x_0))+14.97*(0.6098*x_1*x_1)+2.66*log(0.9475*(0.0561*x_0*x_1))
```

search for 1994, there is a `x_0))1994.09`. I forgot to store the seed to generate this one example, tho :-D  but it seems to happen in 1 in 10 runs.
