### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ed0001tt** [cavalab/feat#291]
conda env create >>> Failed
Solution:
modify environment.yml to 

name: featenv
channels:
    - conda-forge
dependencies:
    - python=3.10
    - setuptools
    - wheel

Then...
conda activate featenv
conda install -c conda-forge pandas scikit-learn cmake ninja eigen cython shogun-cpp
python -m pip install eigency
python -m pip install pmlb
python -m setup.py install

**Comment by lacava** [comment]
could you share the whole output so I can try to reproduce?

**Comment by lacava** [comment]
i have confirmed the most up to date instructions and versions (commit https://github.com/cavalab/feat/commit/51816f42e2c6a36a42771f6868a0e8397a0146eb) for the environment and installation are working locally and on github tests.
