### ISSUE TITLE
add more ML options

### ISSUE THREAD

**Issue by lacava** [cavalab/feat#60]
need to add more ML options to ml class. 
- [x] liblinear (logistic regression) 
- [x] svm 
- [ ] nearest centroid

**Comment by lacava** [comment]
- use CLibLinear for LR and SVM: http://shogun.ml/api/latest/classshogun_1_1CLibLinear.html
- pass LIBLINEAR_SOLVER_TYPE to specify LR or SVM
- in get_weights(), add LR to type comparison for returning from get_w() function

for CART and RandomForest, we need to return weights based on information criterion of the features.

**Comment by tilakhere** [comment]
commits https://github.com/lacava/fewtwo/commit/3994e22ed7cea987a6a59252289b67b7480857f3 and https://github.com/lacava/fewtwo/commit/3534ac8c465b952cd7d0176ae44f0b45d6fd6ab7

**Comment by tilakhere** [comment]
commit https://github.com/lacava/fewtwo/commit/31ce90eeffe16ae1badc865c672b8a5fcb498fdf

integrated SVM and LR in ml_method branch.

used CBinaryLabels in evaluation class for ml = SVM && classification || ml = LR
